version: '3.10'
services:
  app:
    build: .
    command: bash 
    tty: true
    ports:
      - "XXXX:XXXX"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: review
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
